/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;


public class pantallaCrearPartida extends javax.swing.JFrame {

    public pantallaCrearPartida() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblMotoApuesta = new javax.swing.JLabel();
        lblNumCasillas1 = new javax.swing.JLabel();
        lblFondoFijo1 = new javax.swing.JLabel();
        lblNumfichas1 = new javax.swing.JLabel();
        lblNumJugador1 = new javax.swing.JLabel();
        imgPatolli2 = new javax.swing.JLabel();
        imgPatolli = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnCancelaar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jboxFichas = new javax.swing.JComboBox<>();
        jboxNumCasillad = new javax.swing.JComboBox<>();
        txtMonto = new javax.swing.JTextField();
        txtFondo1 = new javax.swing.JTextField();
        jboxNumJugador4es = new javax.swing.JComboBox<>();
        Fondo = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        btnJugar.setBackground(new java.awt.Color(0, 153, 255));
        btnJugar.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(255, 255, 255));
        btnJugar.setText("Jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurar partida");

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Configurar partida");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        lblMotoApuesta.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        lblMotoApuesta.setText("Monto a apostar");
        jPanel3.add(lblMotoApuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 140, -1));

        lblNumCasillas1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        lblNumCasillas1.setText("Número de casillas");
        jPanel3.add(lblNumCasillas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 170, -1));

        lblFondoFijo1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        lblFondoFijo1.setText("Fondo fijo por apostar");
        jPanel3.add(lblFondoFijo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 190, -1));

        lblNumfichas1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        lblNumfichas1.setText("Fichas por jugador");
        jPanel3.add(lblNumfichas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 160, -1));

        lblNumJugador1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        lblNumJugador1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNumJugador1.setText("Número máximo de jugadores");
        lblNumJugador1.setToolTipText("");
        jPanel3.add(lblNumJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 250, -1));

        imgPatolli2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/monoPato.png"))); // NOI18N
        jPanel3.add(imgPatolli2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 90, 80));

        imgPatolli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/monoPato.png"))); // NOI18N
        jPanel3.add(imgPatolli, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 90, 80));

        btnCrear.setBackground(new java.awt.Color(0, 153, 255));
        btnCrear.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear partida");
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
        });
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel3.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 140, 40));

        btnCancelaar.setBackground(new java.awt.Color(0, 153, 255));
        btnCancelaar.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnCancelaar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelaar.setText("Cancelar");
        btnCancelaar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelaarMouseClicked(evt);
            }
        });
        btnCancelaar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaarActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelaar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 130, 40));

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("*");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        jboxFichas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));
        jboxFichas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jboxFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 110, -1));

        jboxNumCasillad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "9", "10", "11", "12", "13", "14" }));
        jboxNumCasillad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jboxNumCasillad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 110, -1));

        txtMonto.setText("$");
        jPanel3.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 110, 20));

        txtFondo1.setText("$");
        jPanel3.add(txtFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 110, 20));

        jboxNumJugador4es.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        jboxNumJugador4es.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.add(jboxNumJugador4es, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 110, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoa.png"))); // NOI18N
        jPanel3.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -30, 650, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
       
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
    
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCancelaarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaarActionPerformed
     
    }//GEN-LAST:event_btnCancelaarActionPerformed

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        pantllaColor color = new pantllaColor();
        color.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearMouseClicked

    private void btnCancelaarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelaarMouseClicked
        pantallaOpcionInvAnfi opcion = new pantallaOpcionInvAnfi();
        opcion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelaarMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(pantallaCrearPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(pantallaCrearPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(pantallaCrearPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(pantallaCrearPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new pantallaCrearPartida().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnCancelaar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel imgPatolli;
    private javax.swing.JLabel imgPatolli2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jboxFichas;
    private javax.swing.JComboBox<String> jboxNumCasillad;
    private javax.swing.JComboBox<String> jboxNumJugador4es;
    private javax.swing.JLabel lblFondoFijo1;
    private javax.swing.JLabel lblMotoApuesta;
    private javax.swing.JLabel lblNumCasillas1;
    private javax.swing.JLabel lblNumJugador1;
    private javax.swing.JLabel lblNumfichas1;
    private javax.swing.JTextField txtFondo1;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
