/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;


public class pantllaColor extends javax.swing.JFrame {

    public pantllaColor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupoRadio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnRadioAmarillo = new javax.swing.JRadioButton();
        btnRadioVerde2 = new javax.swing.JRadioButton();
        btnRadioRosa1 = new javax.swing.JRadioButton();
        btnRdioRojo = new javax.swing.JRadioButton();
        Rosa = new javax.swing.JLabel();
        Rojo = new javax.swing.JLabel();
        Amarillo = new javax.swing.JLabel();
        verde = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imgPatolli = new javax.swing.JLabel();
        imgPatolli2 = new javax.swing.JLabel();
        btnUnirse = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGrupoRadio.add(btnRadioAmarillo);
        btnRadioAmarillo.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnRadioAmarillo.setText("Amarillo");
        btnRadioAmarillo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(btnRadioAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 90, -1));

        btnGrupoRadio.add(btnRadioVerde2);
        btnRadioVerde2.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnRadioVerde2.setText("Verde");
        btnRadioVerde2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(btnRadioVerde2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 90, -1));

        btnGrupoRadio.add(btnRadioRosa1);
        btnRadioRosa1.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnRadioRosa1.setText("Rosa");
        btnRadioRosa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(btnRadioRosa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 90, -1));

        btnGrupoRadio.add(btnRdioRojo);
        btnRdioRojo.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnRdioRojo.setText("Rojo");
        btnRdioRojo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(btnRdioRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 90, -1));

        Rosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frosa.png"))); // NOI18N
        jPanel1.add(Rosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        Rojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/frojo.png"))); // NOI18N
        jPanel1.add(Rojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        Amarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/famarillo.png"))); // NOI18N
        jPanel1.add(Amarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        verde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fverde.png"))); // NOI18N
        jPanel1.add(verde, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PATOLLI");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        imgPatolli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1patolli.png"))); // NOI18N
        jPanel1.add(imgPatolli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 80));

        imgPatolli2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1patolli.png"))); // NOI18N
        jPanel1.add(imgPatolli2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 90, 80));

        btnUnirse.setBackground(new java.awt.Color(0, 153, 255));
        btnUnirse.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        btnUnirse.setForeground(new java.awt.Color(255, 255, 255));
        btnUnirse.setText("Unirse a la partida");
        btnUnirse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUnirseMouseClicked(evt);
            }
        });
        btnUnirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseActionPerformed(evt);
            }
        });
        jPanel1.add(btnUnirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 170, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoa.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseActionPerformed

        
    }//GEN-LAST:event_btnUnirseActionPerformed

    private void btnUnirseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnirseMouseClicked
        pantallaTableroEspera tablero = new pantallaTableroEspera();
        tablero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUnirseMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(pantllaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(pantllaColor.class.getName()).log(java.util.logging.btnRadioAmarilloLevel.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(pantllaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.loggibtnRadioRosang.Logger.getLogger(pantllaColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//     btnRdioRojo           new pantllaColor().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amarillo;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Rojo;
    private javax.swing.JLabel Rosa;
    private javax.swing.ButtonGroup btnGrupoRadio;
    private javax.swing.JRadioButton btnRadioAmarillo;
    private javax.swing.JRadioButton btnRadioRosa1;
    private javax.swing.JRadioButton btnRadioVerde2;
    private javax.swing.JRadioButton btnRdioRojo;
    private javax.swing.JButton btnUnirse;
    private javax.swing.JLabel imgPatolli;
    private javax.swing.JLabel imgPatolli2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel verde;
    // End of variables declaration//GEN-END:variables
}
